### ISSUE TITLE
Compile error: "~/Downloads/Symphonium-master/libs/RTMIDI/RtMidi.h:138: error: expected identifier     MACOSX_CORE 1,    /*!< Macintosh OS-X CoreMIDI API. */     ^" when building for MacOS

### ISSUE THREAD

**Issue by MattyMan05** [ttdm/Symphonium#4]

**Comment by ttdm** [comment]
Hi, its written pretty clearly in the readme, I don't own a mac so i cannot build/use/test the soft properly on mac. 

All the library I used are cross-platform so it **should** work if you take a bit of time to try to build it (which should basically be just properly linking everything).

I'm sorry I cannot help you on that one !

**Comment by magnusviri** [comment]
I can provide a Mac you can remote into if that helps. I don't really have the time to build and test it myself. I'd use it if you had a downloadable.

**Comment by ttdm** [comment]
Since multiple people asked for it, I will look into it during the week. 

I will get back to you @magnusviri if I need it.

**Comment by ttdm** [comment]
It took me more time than initially planed to get a mac but when i finally found one, it was too old and i couldn't install QTcreator on it. 

@magnusviri if your offer for a remote access is still there, I'd like to take it. You can ask/send infos using thibaut.tezenas(at)protonmail.com

**Comment by ttdm** [comment]
As expected, linking was pretty straight forward. The current commit should compile on macOS. 

You can also download an image at : 
https://plik.vulpecula.fr/file/taLNos3dM9gIGfmG/ek040cj7LlCCebFG/Symphonium.zip
From my tests : 
- the app should run and it should be possible to read MIDIFiles.
- I also connected it to an artificial MIDI input/output and it worked fine.

I don't know if you will have sound directly on your OS (it's the case in windows but not using linux) or not; but you should have a signal on your MIDI output. 

Hopefully It will work and thanks again for your offer @magnusviri !

**Comment by ttdm** [comment]
From user feedback, it looks like the image would work with a MIDI keyboard that has a MIDI IO and a sound output on it. 

But it doesn't produce any sound directly on the computer. Just like using a linux. I'm closing this compiling issue, since it is resolved.

For the sound issue, for the moment please refer to #3 to have sound directly on the computer for linux/OSX. 
I might add a synthesizer in a near future.
