### ISSUE TITLE
[Linux] Symphonium crashes after playing first key

### ISSUE THREAD

**Issue by TJesionowski** [ttdm/Symphonium#7]
Console displays:
```
MidiInAlsa::getPortName: error looking for port name!

MidiOutAlsa::getPortName: error looking for port name!

MidiInAlsa::getPortName: error looking for port name!

MidiOutAlsa::getPortName: error looking for port name!
```

[Sound file](https://bitmidi.com/uploads/86046.mid)

I've opened the same file on the same setup with other software (PianoBooster) and it played without crashing. There were errors, but those errors always occured on the same note and almost all notes played so I doubt the connection is at fault.

**Comment by ttdm** [comment]
Hi, 

Most likely you didn't select any MIDI port and when if it fails silently with most backend, it isn't the case with ALSA. 

Can you tell me if you selected a MIDI port in Option -> Select MIDI port ? 
Does it crash once you select a MIDI port ? 

Edit : I recently added some options following a mail exchange with a user. He also told me that it felt weird not having any sound before selecting a MIDI port. I will adress this issue before updating the new version.

**Comment by ttdm** [comment]
It has been improved 9 month ago and improved again today which should solve this issue. 

Also it is quite old and my previous answer wasn't answered so I'm closing this today.
